### ISSUE TITLE
About leaderboard-2.0 branch

### ISSUE THREAD

**Issue by Simon-Pu** [carla-simulator/leaderboard#111]
May I know which version of CARLA and scenario_runner are required for running with the leaderboard-2.0 branch?

**Comment by glopezdiest** [comment]
**WE ARE ACTIVELY DEVELOPING UNDER IT**, so procede at your own discretion. I'd recommend against using it

As of right now, all repos need the `leaderboard-2.0` branch (CARLA, ScenarioRunner and the Leaderboard). Also, for some periods of time, our CARLA content might not `master`, but another branch instead.
