### ISSUE TITLE
scenrio_runner 0.9.13 crashes server on CARLA 0.9.13

### ISSUE THREAD

**Issue by klaus99815** [carla-simulator/leaderboard#113]
Hi,
I try to use 0.9.13 Carla and 0.9.13 SR, and partially modified leaderboard.
But after only evaluating 30 short routes, Carla collapsed.
Is this expected?
![image](https://user-images.githubusercontent.com/101232999/162116165-d46e04c2-ff25-4762-a62b-3a880e204ec4.png)
I saw that [the issue ](https://github.com/carla-simulator/scenario_runner/issues/839)also mentioned related problems. 0.9.12 Carla crashed due to multiple iterations.

Is there any solution at present?
I would appreciate any help you could provide me!

**Comment by klaus99815** [comment]
I tried using 0.9.12 Carla and SR. After running the same route for about 15 seconds for 30 times, the Carla server crashed...

Does anyone have any suggestions? Is there something wrong?

**Comment by glopezdiest** [comment]
> Is this expected?

Kind of. As far as we know, CARLA has some memory deletion issues that can acummulate over time, resulting in a memory crash after long sessions. If I recall correctly, it is related to sensor destruction. We are working on fixing it, and the CARLA *dev* branch already has some improvements that partially fix this.
