### ISSUE TITLE
Bug in infractions/km calculation in compute_global_statistics

### ISSUE THREAD

**Issue by Kait0** [carla-simulator/leaderboard#117]
I think there is a bug in the computation of the infractions / km metrics in the current leaderboard repository (master):
The file is leaderboard/utils/statistics_manager.py
Function  def compute_global_statistics(self, total_routes):

    ...
    if self._registry_route_records:
            for route_record in self._registry_route_records:
                     global_record.scores['score_route'] += route_record.scores['score_route']
                     global_record.scores['score_penalty'] += route_record.scores['score_penalty']
                     global_record.scores['score_composed'] += route_record.scores['score_composed']
    
                     for key in global_record.infractions.keys():
                         route_length_kms = max(route_record.scores['score_route'] / 100 * route_record.meta['route_length'] / 1000.0, 0.001)
                         if isinstance(global_record.infractions[key], list):
                              global_record.infractions[key] = len(route_record.infractions[key]) / route_length_kms
                         else:
                              global_record.infractions[key] += len(route_record.infractions[key]) / route_length_kms
     
                     if route_record.status is not 'Completed':
                         global_record.status = 'Failed'
                         if 'exceptions' not in global_record.meta:
                             global_record.meta['exceptions'] = []
                         global_record.meta['exceptions'].append((route_record.route_id,
                                                                  route_record.index,
                                                                  route_record.status))
     
                 for key in global_record.scores.keys():
                     global_record.scores[key] /= float(total_routes)
                 ...

In the line:  
         `global_record.infractions[key] += len(route_record.infractions[key]) / route_length_kms `

The infractions/km from all the individual routes simply get added together, leading to nonsense value that are dependent on the number of routes.
The current code implements the following formula:
![image](https://user-images.githubusercontent.com/4252687/167406646-ac12bb28-be56-439f-b0a8-75f59875bfb7.png)
where c_i is the number of collisions in route, km_i is the number of km driven in route i. N is the number of routes.

A naive fix would be to divide by the number of routes:
![image](https://user-images.githubusercontent.com/4252687/167407022-037101c8-f7e7-4673-a118-558388456840.png)
However this is not exactly the correct calculation.
Slicing the driven km into route segments changes the result of the infraction / km metric and in the worst case can lead to a  [simpsons paradox](https://en.wikipedia.org/wiki/Simpson%27s_paradox).

What we want to compute is the total number of collisions / total number of km driven so the correct formula is:
![image](https://user-images.githubusercontent.com/4252687/167408054-cb2a8b59-f22d-439d-b604-839447ad08b5.png)

which in code would looks something like adding the infractions (per type) as well as adding the driven (!) km to variables outside the for_loop and after the route for loop dividing the counts by the total number of driven kms.

**Comment by Kin-Zhang** [comment]
> leading to nonsense value that are dependent on the number of routes.
![image](https://user-images.githubusercontent.com/4252687/167406646-ac12bb28-be56-439f-b0a8-75f59875bfb7.png)

I knew what you mean here, but the infraction on global record may want to the result as the formula here.

The next one actually cannot seem like the average of collisions on routes kilometers. but average on all kilometers with fading the route concept?

![image](https://user-images.githubusercontent.com/4252687/167408054-cb2a8b59-f22d-439d-b604-839447ad08b5.png)

But I agree with your opinion. since the first one will cause some number really big when the route_length_kms on one route are really small.

**Comment by Kait0** [comment]
As a sidenote one needs to take additional care with the off-road infraction metric. 
Right now I think the leaderboard always reports it as one infraction adding together the total amount of meters driven off road.
So counting does not work for that infraction since it is either 1 or 0.
With the current system one can sum up the (kilo!) meters driven off road (and divide by the total number of km driven) to get a meaningful estimate (maybe multiply by 100 because that is a percentage).

The other option would be to change how off-road is reported and report every single instance where the agent drove off the road (and then just count as usual).

**Comment by glopezdiest** [comment]
Hey @Kait0, thanks for the detailed explanation. I'll take a look at it and report back

**Comment by glopezdiest** [comment]
After some inspection, it does seem to be misscalculated. We are indeed using
![image](https://user-images.githubusercontent.com/58212725/183578651-9e17cd28-6b27-44a8-8ab5-ad8bda76e4b6.png)
to calculate the infractions per km, while in reality we want
![image](https://user-images.githubusercontent.com/58212725/183578728-688ffe21-fdd1-4f53-86ec-fa6fd5e50413.png)

I'll update the Leaderboard as soon as I can with this fix, thanks :slightly_smiling_face:

**Comment by glopezdiest** [comment]
With the coming release of the LB 2.0, this issue has been fixed. It is currently only available in the `leaderboard-2.0` branch, but for those interested, the fix is done in this PR https://github.com/carla-simulator/leaderboard/pull/130/files (along with many other things).
