### ISSUE TITLE
Where to find Map 12

### ISSUE THREAD

**Issue by laurayuzheng** [carla-simulator/leaderboard#141]
Hi guys, 
I'm asking about leaderboard 2.0 routes files. Currently I'm trying to run these routes with ScenarioManager (as I'm interested in the pre-crash typology scenarios). 

I'm trying to find information on how to get map 12 (I can only find Map 11 information online). Currently I'm using CARLA 0.9.13. Is this included in 0.9.13 release of CARLA, or is it an external download?

**Comment by Kin-Zhang** [comment]
Related problems, which CARLA version for leaderboard 2.0 also?

**Comment by glopezdiest** [comment]
Town12 is avaiable as part of the CARLA package used for the Leaderboard 2.0, which you can find in the first steps of the [website](https://leaderboard.carla.org/get_started/)

**Comment by Kin-Zhang** [comment]
@glopezdiest  CALR 0.9.13 didn't have many things that leaderboard requires
1. Town12 is about the map on CALRA not routes code
2.  CARLA 0.9.13 and other version also don't have the constant agenet, errror like here:
```bash
from agents.navigation.constant_velocity_agent import ConstantVelocityAgent
ModuleNotFoundError: No module named 'agents.navigation.constant_velocity_agent'
```
