### ISSUE TITLE
question about version 

### ISSUE THREAD

**Issue by EcustBoy** [carla-simulator/leaderboard#152]
Hi~ I wonder if there is a strict correspondence between **leaderboard** and **carla simulator**? For example, I use carla-0.9.12, which version of leaderboard code should I choose?
Looking forward and thanks much for your reply~

**Comment by PabloVD** [comment]
Each version of the leaderboard is expected to be run with a correspondent version of the carla simulator.
Leaderboard 1 works with 0.9.10.1 and Leaderboard 2 with 0.9.14. You can directly download the proper package version from the [get started page](https://leaderboard.carla.org/get_started/).
