### ISSUE TITLE
Boost.Python.ArgumentError: Python argument types in WorldSettings.__init__(WorldSettings) did not match C++ signature:

### ISSUE THREAD

**Issue by jingyue01** [carla-simulator/leaderboard#157]
>test_run.sh
/home/yeda/thesis/leaderboard/leaderboard/leaderboard_evaluator.py:21: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/home/yeda/thesis/leaderboard/leaderboard/leaderboard_evaluator.py", line 478, in <module>
    main()
  File "/home/yeda/thesis/leaderboard/leaderboard/leaderboard_evaluator.py", line 467, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "/home/yeda/thesis/leaderboard/leaderboard/leaderboard_evaluator.py", line 79, in __init__
    self.client, self.client_timeout, self.traffic_manager = self._setup_simulation(args)
  File "/home/yeda/thesis/leaderboard/leaderboard/leaderboard_evaluator.py", line 178, in _setup_simulation
    spectator_as_ego = False
Boost.Python.ArgumentError: Python argument types in
    WorldSettings.__init__(WorldSettings)
did not match C++ signature:
    __init__(_object*, bool synchronous_mode=False, bool no_rendering_mode=False, double fixed_delta_seconds=0.0, bool substepping=True, double max_substep_delta_time=0.01, int max_substeps=10, float max_culling_distance=0.0, bool deterministic_ragdolls=False, float tile_stream_distance=3000.0, float actor_active_distance=2000.0)
    __init__(_object*)

I am using a ubuntu virtual machine to run the client, and Windows to run the Carla server.

**Comment by heng-yuwen** [comment]
At ```leaderboard/leaderboard/leaderboard_evaluator.py```, line 178, delete parameter ```spectator_as_ego = False ```

**Comment by jingyue01** [comment]
> At `leaderboard/leaderboard/leaderboard_evaluator.py`, line 178, delete parameter `spectator_as_ego = False `.
> 
> However, this is not the right solution. You should download the carla leaderboard version from https://leaderboard.carla.org/get_started/ instead.

Thank you very much. I got it.
