### ISSUE TITLE
Incompatibility Issue between CARLA Leaderboard 2.0 and CARLA 0.9.14 API

### ISSUE THREAD

**Issue by SailorBrandon** [carla-simulator/leaderboard#163]
I have encountered an incompatibility between CARLA Leaderboard 2.0 and CARLA 0.9.14 API. The issue arises from the use of a variable named `spectator_as_ego` in the class `carla.WorldSettings` within the CARLA Leaderboard 2.0 codebase. However, this variable does not exist in the CARLA 0.9.14 API, leading to compatibility problems.

The error was caused by 
https://github.com/carla-simulator/leaderboard/blob/da62c1b75124d6f24b47d4218e0f7169445441ae/leaderboard/leaderboard_evaluator.py#L178

**Comment by SailorBrandon** [comment]
The library `roslibpy` should also be added to the requirements.txt.

**Comment by ajperry2** [comment]
Could this be coded up but not documented in carla? I'm looking at this [line](https://github.com/carla-simulator/carla/blob/cead6d1b05e89ad84df80984f62daba57bb50e55/PythonAPI/carla/source/libcarla/World.cpp#L167)

**Comment by Daraan** [comment]
I think it was introduced in 0.9.15 https://github.com/carla-simulator/carla/commit/1501a13b1e5b15f2aaf34132466d983a354e2ca6

**Comment by glopezdiest** [comment]
Hello @SailorBrandon. Yes, you are correct. As everyone has pointed out, the `spectator_as_ego` was introduced at 0.9.15, which makes it non compatible with the Leaderboard 2.0.

With that said, the `spectator_as_ego` variable just makes the initialization of the large maps more efficient by not loading some unnecessary tiles. If you really want to use CARLA 0.9.14, feel free to just remove that line, and everything should work fine.

Closing the issue, but feel free to reopen it if there are any other doubts
