### ISSUE TITLE
OpenDRIVE data never retrieved when it is the only sensor.

### ISSUE THREAD

**Issue by Daraan** [carla-simulator/leaderboard#169]
I wanted to check out the opendrive_map sensor but never got any `input_data`; not setting up other sensors for this purpose.

I tracked this bug down to this line of code that always aborts the data retrieval:

https://github.com/carla-simulator/leaderboard/blob/111a48f9099c08a2f1068ee8aea2ad56ce52ef9d/leaderboard/envs/sensor_interface.py#L230-L232

With only an opendrive_map sensor this is equal to `1 == 0+1` and always breaks -> returns empty dict.

Shortly also noted in #50

**Comment by glopezdiest** [comment]
@Daraan That does seem to be the case. We'll fix it ASAP
