### ISSUE TITLE
Failed to capture data using a rgb-camera with a time-out error.

### ISSUE THREAD

**Issue by milk-bottle-liyu** [carla-simulator/leaderboard#171]
I am struggling to capture data with the offical log in CarlaLeaderboard 2.0. The camera sensor always failed to send back the data and raise a timeout error. I only cutoff some sensors in the example capture python script and add an additional sensor limit to the agent wrapper. I tried to increase the time limit of the queue to 60s , but it still failed. Please, can any one can help with it?

**Comment by glopezdiest** [comment]
Hello @milk-bottle-liyu, we already discussed this through Discord but I'm leaving the answer here in case other users have the same issue. 

Sometimes the sensors fail to send their data on the first several ticks, so the solutions comes by adding several ticks after the sensor creations.

This is actually an issue, and so the script has been updated to fix it, and can be found in [here](https://leaderboard.carla.org/get_started/#42-training-database-creation-tools)
