### ISSUE TITLE
What is the difference between the ScenarioManager in leaderboard and that in scenario_runner?

### ISSUE THREAD

**Issue by emailweixu** [carla-simulator/leaderboard#48]
The code looks very similar. Why does leaderboard need to have a separate implementation and what is the difference?

**Comment by glopezdiest** [comment]
Hey @emailweixu. As of right now, they might very well be identical (this also happens with other files). However, it's just another measure of caution to ensure their content is known, as they are quite important. Additionally, the two versions might diverge, so its such good to duplicate them now and avoid the trouble later
