### ISSUE TITLE
How to use MAP track in leaderboard

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/leaderboard#50]
In [leaderboard](https://leaderboard.carla.org/) website, there are two tracks -- one is SENSORS track, the other is MAP track. In this repository, the SENSORS track is set as default in /leaderboard/autoagents/autonomous_agent.py

```
class AutonomousAgent(object):
    def __init__(self, path_to_conf_file):
        self.track = Track.SENSORS
        self._global_plan = None
        self._global_plan_world_coord = None
```

When I set self.track as Track.MAP in my agent by 

```
class HDMapAgent(BaseAgent):
    def setup(self, path_to_conf_file):
        super().setup(path_to_conf_file)
        self.track = Track.MAP
        self.converter = Converter()

```
and After I added an opendrive_map sensor by 

```
   def sensors(self):
        result = super().sensors()
        result.append({
            'type': 'sensor.opendrive_map',
            'reading_frequency': 20,
            'id': 'opendrive_map'
            })
```

An error occurred as :

`Could not setup required agent due to 'NoneType' object is not iterable.`

I don't know how to set up an agent using MAP track. Is there any reference for that?

**Comment by glopezdiest** [comment]
Hey @nuomizai, sorry for the delay. Could you give a more detail about this error, or is this the only message shown?

To use the MAP track, you only need to do *self.track = Track.MAP* as you are already doing, and run the script with the *track* argument equal to *MAP*.

Going on a tangent here, there no need to call the *setup*, and *sensors* functions of *AutonomousAgent*, as they are completely empty.

**Comment by nuomizai** [comment]
> Hey @nuomizai, sorry for the delay. Could you give a more detail about this error, or is this the only message shown?
> 
> To use the MAP track, you only need to do _self.track = Track.MAP_ as you are already doing, and run the script with the _track_ argument equal to _MAP_.
> 
> Going on a tangent here, there no need to call the _setup_, and _sensors_ functions of _AutonomousAgent_, as they are completely empty.

Thank you, @glopezdiest . I followed the instructions on [leaderboard](https://leaderboard.carla.org/get_started/) website and have accessed to the opendrive sensor successfully!

**Comment by glopezdiest** [comment]
Good to hear :+1:

**Comment by Daraan** [comment]
I struggled with this a bit too, there are two points to note:

1. Return a list, with the sensors object else you will get some error involving `None` like described above
2. Using ONLY 'sensor.opendrive_map' will never return the data because of [this statement](https://github.com/carla-simulator/leaderboard/blob/111a48f9099c08a2f1068ee8aea2ad56ce52ef9d/leaderboard/envs/sensor_interface.py#L230):

```py
                # Don't wait for the opendrive sensor, if there are at least two sensors
                if self._opendrive_tag and self._opendrive_tag not in data_dict.keys() \
                        and len(self._sensors_objects.keys()) == len(data_dict.keys()) + 1: # <-- if only one key this will always break
                    break
``
