### ISSUE TITLE
lidar point cloud data have high variance in x-axis

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/leaderboard#54]
I created a lidar sensor as:
```
        {
            'type': 'sensor.lidar.ray_cast',
            'x': 0.7, 'y': -0.4, 'z': 3,
            'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
            'id': 'LIDAR'
        },
```

But I found the lidar point cloud have a high variance in x-axis. So, I output the maximum and minimum value for axis x,y,z at each timestep by

```
        point_cloud = []
        for location in input_data['LIDAR'][1]:
            point_cloud.append([location[0], location[1], -location[2]])
        point_cloud = np.array(point_cloud)

        print('timestep:', self.step)
        print('x: ', np.max(point_cloud[:, 0]), ',', np.min(point_cloud[:, 0]))
        print('y: ', np.max(point_cloud[:, 1]), ',', np.min(point_cloud[:, 1]))
        print('z: ', np.max(point_cloud[:, 2]), ',', np.min(point_cloud[:, 2]))

```
And the result was as follows:

=======================result================================
timestep: 1

x:  151.4036 , -6.1035153e-06

y:  159.78447 , -156.04468

z:  34.19531 , -3.0915384

timestep: 2

x:  1.0375977e-05 , -193.3553

y:  154.51567 , -194.5679

z:  17.86496 , -3.0915384

timestep: 3

x:  151.40314 , -6.1035153e-06

y:  159.78447 , -156.04468

z:  34.195312 , -3.0911043

timestep: 4

x:  1.4648437e-05 , -193.35521

y:  154.51567 , -194.56285

z:  17.86496 , -3.090934

timestep: 5

x:  151.40294 , -2.746582e-05

y:  159.78447 , -156.04468

z:  34.19531 , -3.3909142

timestep: 6

x:  1.15966795e-05 , -193.35521

y:  154.51567 , -194.56355

z:  17.864958 , -3.0910094

timestep: 7

x:  151.40315 , -4.5776364e-06

y:  159.78447 , -156.04468

z:  34.19531 , -3.0911257

timestep: 8

x:  9.460449e-06 , -193.35526

y:  154.51567 , -194.56554

z:  17.864964 , -3.0912502

timestep: 9

x:  151.40341 , -1.2207031e-06

y:  159.78447 , -156.04468

z:  34.19531 , -3.091369

timestep: 10

x:  1.4648437e-05 , -193.35529

y:  154.51567 , -194.56749

z:  17.864962 , -3.0914743

=====================================================
As you can see, the y and z axis have a relatively stable value range while the x-axis value has a high variance. For example, in timestep 9, the minimum value of x-axis is around 0 (-1.2207031e-06). But in step 10, the minimum x-axis value is -193.35529. This will influence the performance because every timestep the agent can only have access to a half information of the environment. Does anyone know how I can solve this?

**Comment by ap229997** [comment]
'rotation_frequency' for lidar should be set to 20 in ```leaderboard/autoagents/agent_wrapper.py```

**Comment by nuomizai** [comment]
> 'rotation_frequency' for lidar should be set to 20 in `leaderboard/autoagents/agent_wrapper.py`

Thank you, @ap229997 . It solved my problem :)
