### ISSUE TITLE
How to change the lifetime of the traffic light

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/leaderboard#62]
I want to change the lifetime of the red, green and yellow traffic light in leaderboard. But I didn't find the right place. Does anyone know where to change these parameter settings?

**Comment by glopezdiest** [comment]
hey @nuomizai, what is your objective here? and what do you mean by *lifetime*? In principle, you can change all traffic light related parameters at the [carla.TrafficLight](https://carla.readthedocs.io/en/latest/python_api/#carlatrafficlight) class, and you can get any traffic light from the *carla.World.get_actors()* function.

For the leaderboard, you'd have to create an atomic in parallel / series to another that sets them to their desired value, and that's it. I don't think we have one created by default though, but it shouldn't be too hard.
