### ISSUE TITLE
What units are the gnss measurements in?

### ISSUE THREAD

**Issue by ICGog** [carla-simulator/leaderboard#63]
I've updated CARLA from 0.9.9.4 to 0.9.10, and I've noticed that the units of the gnss measurements have changed. Can you please clarify what the units are?

I've done a test in the second scenario of the training routes and got the following first readings:
`CARLA_version, latitude, longitude, altitude`
`CARLA 0.9.9.4, 48.999461259289234, 8.001663866110341, 0.027095741455013922`
`CARLA 0.9.10, -0.0005387375004914929, 0.0010921803470367757, 0.03183420454388397`

The values received in CARLA 0.9.9.4 are in degrees, and are correct.

**Comment by glopezdiest** [comment]
Hey, this seems to be a problem with the default latitude and longitude of the map. What town are you seeing this at?

**Comment by ICGog** [comment]
I'm seeing this is town 1. I've ran the experiment on route 1 from the training routes.

**Comment by glopezdiest** [comment]
Indeed, we recently changed the OpenDrive maps but the georeference wasn't carried over between versions so the numbers differ (for all maps). Previously, the georeference was (lat = 49, lon = 8) but now its (lat = 0, lon = 0).

In the end, it is just a matter of translating the points to the new georefence, the units haven't changed, and the relative movement will still be the same. Anyhow, we will fix that, I'll comment back here when this is changed.

**Comment by glopezdiest** [comment]
After some discussion, we decided to keep the georeference at (lat = 0, lon = 0), as it simplifies some calculus plus the previous one (lat = 49, lon = 8) was chosen arbitrarily, so there is no need to keep it. Again, this is just a translation so unless the previous georeference was hard-coded somewhere, you shouldn't see any difference in your results.
