### ISSUE TITLE
ERROR: trying to create rpc server for traffic manager; but the system failed to create because of bind error.

### ISSUE THREAD

**Issue by nuomizai** [carla-simulator/leaderboard#73]
I got that error when I ran the main function in leaderboard_evaluator.py in a multiprocessing way to train my DRL agent. I also changed the arguments, the code was as follows:

```
import torch.multiprocessing as mp

.
.
.

    for rank in range(2):
        port = 8000 + 100 * (rank + 1)
        t = mp.Process(target=main, args=(
            str(port), result_root_path, rank, traffic_light, counter, shared_model, shared_grad_buffers,
            son_process_counter))
        t.start()
        processes.append(t)

    for t in processes:
        t.join()

```

The 'port' was the main port used by CARLA server and client. I initialized two subprocess, while the first worked well but the second subprocess got the error as:

`trying to create rpc server for traffic manager; but the system failed to create because of bind error.`

I found that there is only one place setting the port of traffic manager, in `scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py`  in class ChangeAutoPilot. But the code `self._tm = CarlaActorPool.get_client().get_trafficmanager()` was not been called. 

Does anyone know where to change the port of traffic manage?

**Comment by glopezdiest** [comment]
Hey @nuomizai, the *leaderboard_evaluator.py* already has the *--trafficManagerPort* argument to set the port of the TrafficManager to the desired one. Is that what you are looking for?

**Comment by nuomizai** [comment]
> Hey @nuomizai, the _leaderboard_evaluator.py_ already has the _--trafficManagerPort_ argument to set the port of the TrafficManager to the desired one. Is that what you are looking for?

Hey @glopezdiest , thank you sooo much! It seemed that I used an old version of leaderboard so that I didn't find the place to set `traffic_manager_port`. I followed the code in the lastest version of _leaderboard_ and _scenario_runner_,  and successfully set the port for my traffic manager. Thank you again!

**Comment by glopezdiest** [comment]
Glad to hear it works :slightly_smiling_face:. Closing the issue
