### ISSUE TITLE
No module named 'srunner'

### ISSUE THREAD

**Issue by AnneCCollin** [carla-simulator/leaderboard#77]
Hello,

I followed the instructions from this page https://leaderboard.carla.org/get_started/ (using same carla version)
After definition my environment variables, I try running ./scripts/run_evaluation.sh, and I get a ModuleNotFoundError: No module named 'srunner'. I checked and my PYTHONPATH contains the carla/leaderboard/scenario_runner paths, as described in the tutorial, and I am in the correct conda env. Any idea as to what is happening? My OS is Ubuntu 16.04

**Comment by glopezdiest** [comment]
Hey @AnneCCollin that error is because your PYTHONPATH isn't correctly detecting ScenarioRunner. Could you check if that's the case?

**Comment by AnneCCollin** [comment]
Thank you, in the end, the PYTHONPATH was correct, but putting the scenario_runner folder into leaderboard/ solved it.
