### ISSUE TITLE
UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment

### ISSUE THREAD

**Issue by raozhongyu** [carla-simulator/leaderboard#83]
Thanks for your great work. I meet  this question of "UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment" when followed the "Create Autonomous Agents with the Leaderboard" in https://leaderboard.carla.org/get_started/#21-first-steps-with-the-leaderboard. Can you give some suggestions? Thanks a lot.

**Comment by raozhongyu** [comment]
Meanwhile, I also meet the error of "AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager' '

**Comment by Jidenna** [comment]
Were you able to figure this out? I am also getting both errors

**Comment by Abyss-J** [comment]
@raozhongyu Sorry to bother you, but I also encountered these two problems. Can you tell me how to solve them
