### ISSUE TITLE
Error when running the leaderboard evaluator after building Dockerfile.master to use it with Python 2.7 egg

### ISSUE THREAD

**Issue by hatem-darweesh** [carla-simulator/leaderboard#84]
Dear CARLA team, 

Here is my issue: 
I want to use CARLA Python APIs 2.7 .egg 
On my local machine, it works fine by doing these steps: 
1- export PYTHONPATH=$PYTHONPATH:CARLA_0.9.10.1/PythonAPI/carla/dist/carla-0.9.10-py2.7-linux-x86_64.egg
2- agent:  ros_agent.py 
3- Evaluator: I run command: pythong leaderboard_evaluator.py

But when I try to build the Dockerfile.master here comes the problems. 
1- I don't use ros_agent, I use npc_agent for testing 
2- successfully build it, and was able to run the agent inside docker with python3

Then I modified Docker as the follows: 
- replace ubuntu 16 with -> FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
- add required additional libraries 

After successful docker build, and fix a lot of issues , finally I stuck with this error: 

`Traceback (most recent call last):
  File "/workspace/leaderboard/leaderboard/leaderboard_evaluator.py", line 31, in <module>
    from leaderboard.scenarios.scenario_manager import ScenarioManager
  File "/workspace/leaderboard/leaderboard/scenarios/scenario_manager.py", line 25, in <module>
    from leaderboard.autoagents.agent_wrapper import AgentWrapper, AgentError
  File "/workspace/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 20, in <module>
    from leaderboard.envs.sensor_interface import CallBack, OpenDriveMapReader, SpeedometerReader, SensorConfigurationInvalid
  File "/workspace/leaderboard/leaderboard/envs/sensor_interface.py", line 8, in <module>
    import queue
ImportError: No module named queue`

Can anyone help ! 
Thanks

**Comment by hatem-darweesh** [comment]
This was solved by suggestion from luis 
https://discord.com/channels/444206285647380482/551506571608326156/829086742337421382

**Comment by marcusvinicius178** [comment]
Hi @luis2r @hatem-darweesh I am facing the same issue. However the link of discord is unavailable. Could you please tell me how did you solve?
